"""
Django settings for youtube_search_download project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jhk$3okdo7j0+)pn&ww6g14cw=lxhd2ji5+dw==x$iui&o58@a'

# SECURITY WARNING: don't run with debug turned on in production!
# CHANGED: Set to False for production deployment. 
# Change back to True if you are testing on your local laptop.
DEBUG = False

# ALLOWED_HOSTS = ['*']
raw_allowed_hosts = os.getenv('ALLOWED_HOSTS')
ALLOWED_HOSTS = raw_allowed_hosts.split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'master',
    'rebux'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CHANGED: WhiteNoise must be listed directly after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==========================================
# BULLETPROOF SUPABASE SESSION CONFIGURATION
# ==========================================

# 1. Force Django to store sessions in the database (This is the default, but good to lock in)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# 2. Force the cookie to survive for 30 days. 
# (By default, Django sets this to 1209600 seconds, which is exactly 2 weeks)
SESSION_COOKIE_AGE = 2592000 

# 3. Ensure they don't lose progress if they close the browser tab 
# (This defaults to False, but we explicitly declare it for safety)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ROOT_URLCONF = 'youtube_search_download.urls'

raw_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = raw_csrf_origins.split(',')

WSGI_APPLICATION = 'youtube_search_download.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Update this line to point to your new root templates folder
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CHANGED: Added STATIC_ROOT. This fixes the "ImproperlyConfigured" error.
# It tells Django where to collect files during deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CHANGED: Enable WhiteNoise storage to serve files efficiently in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
UNSPLASH_API_KEY = os.getenv("UNSPLASH_API_KEY")
GOOGLE_SEARCH_API_KEY = os.getenv("GOOGLE_SEARCH_API_KEY")
GOOGLE_SEARCH_CX = os.getenv("GOOGLE_SEARCH_CX")


# Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# ==========================================
# RENDER PROXY & COOKIE CONFIGURATION
# ==========================================

# 1. Tell Django it is sitting behind a proxy (Render) that handles HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 2. Enforce secure cookies (since Render provides free HTTPS)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 3. Ensure the browser doesn't block the cookie (Lax is best for standard web apps)
SESSION_COOKIE_SAMESITE = 'Lax'

