# Generated by Django 6.0.2 on 2026-02-21 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('image_1_url', models.URLField(max_length=1000)),
                ('image_2_url', models.URLField(max_length=1000)),
                ('image_3_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_4_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
