# Generated by Django 6.0.2 on 2026-02-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlelevel',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='puzzlelevel',
            name='hint',
            field=models.CharField(default='Keep thinking!', max_length=255),
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
